builds:
  - binary: prestd
    main: ./cmd/prestd/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mipsle
      - mips64le
      - ppc64
      - ppc64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - (?i)typo
    - Merge pull request
    - Merge branch
    - go mod tidy
release:
  github:
    owner: prest
    name: prest

dockers:
  - image_templates:
    - "prest/prest:latest"
    - "prest/prest:{{ .Tag }}"
    - "prest/prest:v{{ .Major }}"
    - "ghcr.io/prest/prest:latest"
    - "ghcr.io/prest/prest:{{ .Tag }}"
    - "ghcr.io/prest/prest:v{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT={{.Commit}}"
    - "--build-arg=DATE={{.Date}}"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
    - "prest/prest:latest-noplugins"
    - "prest/prest:{{ .Tag }}-noplugins"
    - "prest/prest:v{{ .Major }}-noplugins"
    - "ghcr.io/prest/prest:latest-noplugins"
    - "ghcr.io/prest/prest:{{ .Tag }}-noplugins"
    - "ghcr.io/prest/prest:v{{ .Major }}-noplugins"
    dockerfile: Dockerfile.noplugins
    build_flag_templates:
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT={{.Commit}}"
    - "--build-arg=DATE={{.Date}}"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
